version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/opt/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    environment:
     DATABASE_URL: mongodb://root:example@db:27017/
     APP_PORT: 8000

  db:
    image: mongo:4.4.27
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    
    depends_on:
      - db