FROM golang:1.21.5-alpine3.19

RUN apk update && apk add git && rm -rf /var/cache/apk/*

WORKDIR /opt/app

COPY ./app .
COPY ./config .
COPY ./cmd .
COPY ./internal .
COPY ./.air.toml .
COPY ./go.mod .
COPY ./go.sum .

RUN go mod download


RUN go install github.com/cosmtrek/air@latest

CMD [ "air" ]

